// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSafetyReport(ctx context.Context, arg CreateSafetyReportParams) (SafetyReport, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindReportsInBounds(ctx context.Context, arg FindReportsInBoundsParams) ([]SafetyReport, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
